# Generated by Django 5.1.2 on 2024-11-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_case_raised_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
